In [1]:
#Imports
import pandas as pd
import functions as func
import yaml
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

db_locations = func.import_yaml()

#load df
df = pd.read_csv(db_locations['data_raw']['train'])
df_test = pd.read_csv(db_locations['data_raw']['test'])

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.price.describe()

In [ ]:
df.head(20)

In [ ]:
df.fuel_type.value_counts()

In [ ]:
df.isnull().any()

In [ ]:
df.dropna().shape

In [ ]:
df.nunique()

In [ ]:
df.sort_values(by=['fuel_type']).tail(20)

In [ ]:
df.sort_values(by=['accident']).tail(20)

In [ ]:
def update_fuel_type(df):
    df.loc[df['engine'].str.contains('Electric', case=False, na=False), 'fuel_type'] = 'Electric'
    df.loc[df['engine'].str.contains('Gasoline', case=False, na=False), 'fuel_type'] = 'Gasoline'
    df.loc[(df['brand'].str.lower() == 'tesla') & (df['engine'].str.contains('Dual Motor - Standard', case=False, na=False)), 'fuel_type'] = 'electric'
    
    return df

In [ ]:
update_fuel_type(df)
df.tail()

In [ ]:
df.sort_values(by=['fuel_type']).tail(20)

In [ ]:
df.clean_title.value_counts()

In [ ]:
tes_df = df[df['clean_title'] != "Yes"]

In [ ]:
tes_df

In [ ]:
df.accident.value_counts()

In [ ]:
tes_df = df[df['accident'] == "At least 1 accident or damage reported"]

In [ ]:
tes_df.clean_title.isnull().any()

In [ ]:
tes_df = tes_df[tes_df['clean_title'] != "Yes"]

In [ ]:
tes_df

In [ ]:
df['accident']= df['accident'].apply(lambda x:'None reported' if pd.isna(x) else x)

In [ ]:
df

In [ ]:
df['clean_title']= df['clean_title'].apply(lambda x:'No' if pd.isna(x) else x)

In [23]:
df.tail(20)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
188513,188513,Lexus,GS 350 F Sport,2022,82046,Gasoline,3.5L V6 24V PDI DOHC,8-Speed Automatic,Caviar,Black,None reported,No,48990
188514,188514,Ford,Transit-350 XLT,2023,16500,Gasoline,275.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,54000
188515,188515,GMC,Sierra 1500 Denali Ultimate,2023,9978,Gasoline,6.2L V8 16V GDI OHV,10-Speed A/T,White Frost Tri-Coat,Walnut,At least 1 accident or damage reported,Yes,48999
188516,188516,INFINITI,M37 x,2018,16000,Gasoline,330.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,55000
188517,188517,Lincoln,Navigator L Select,2016,115600,Gasoline,380.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,30500
188518,188518,Mercedes-Benz,S-Class S 450 4MATIC,2018,74595,Gasoline,362.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,9-Speed A/T,Black,Black,None reported,Yes,36250
188519,188519,GMC,Yukon Denali,2019,34672,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,None reported,Yes,49900
188520,188520,Mercedes-Benz,GLC 300 GLC 300,2022,18031,Gasoline,2.0 Liter Turbo,Automatic,White,Black,None reported,No,39998
188521,188521,BMW,M240 i xDrive,2019,32000,Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,White,Black,None reported,Yes,36300
188522,188522,GMC,Yukon XL Denali,2018,2043,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,47500
188523,188523,BMW,328 i,2011,239000,Gasoline,230.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed A/T,Black,Black,None reported,Yes,8000
188524,188524,Chevrolet,Camaro 1LT,2019,59692,Gasoline,335.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Red,Black,At least 1 accident or damage reported,Yes,33600
188525,188525,Audi,A4 2.0T Premium quattro,2011,121886,Gasoline,211.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,8-Speed A/T,Gray,Black,None reported,Yes,6000
188526,188526,GMC,Yukon XL Denali,2016,89291,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Red,Black,At least 1 accident or damage reported,Yes,24700
188527,188527,Chevrolet,Camaro Z28,1999,110000,Gasoline,310.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,A/T,White,Gray,None reported,Yes,14500
188528,188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,27500
188529,188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,30000
188530,188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,86900
188531,188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,No,84900
188532,188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,28995

In [11]:
df.isnull().any()

id              False
brand           False
model           False
model_year      False
milage          False
fuel_type        True
engine          False
transmission    False
ext_col         False
int_col         False
accident         True
clean_title      True
price           False
dtype: bool

In [12]:
# Correct way of filling Nan:

df.clean_title.fillna('None reported', inplace = True)
df.accident.fillna('No', inplace = True)

/tmp/ipykernel_8788/4053183464.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.clean_title.fillna('None reported', inplace = True)
/tmp/ipykernel_8788/4053183464.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.accident.fillna('No', inplace = True)

In [6]:
#testing cleaning fucntion

df = func.cleaning_null(df)

In [7]:
df.fuel_type.value_counts()

fuel_type
Gasoline          166021
Hybrid              6833
E85 Flex Fuel       5406
Electric            4999
Diesel              3957
–                    781
Plug-In Hybrid       521
not supported         15
Name: count, dtype: int64

In [8]:
df.isnull().sum()

id              0
brand           0
model           0
model_year      0
milage          0
fuel_type       0
engine          0
transmission    0
ext_col         0
int_col         0
accident        0
clean_title     0
price           0
dtype: int64

In [9]:
null_rows = df[df.isnull().any(axis=1)]

In [10]:
null_rows

Empty DataFrame
Columns: [id, brand, model, model_year, milage, fuel_type, engine, transmission, ext_col, int_col, accident, clean_title, price]
Index: []

In [11]:
df[df['fuel_type'] == '–']

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
532,532,Dodge,Challenger R/T Scat Pack,2021,35000,–,–,8-Speed A/T,Blue,Gray,None reported,Yes,48000
1155,1155,Ford,Mustang GT Premium,2017,143600,–,–,6-Speed M/T,White,Black,At least 1 accident or damage reported,Yes,31000
1307,1307,Toyota,Land Cruiser Base,1994,138033,–,–,A/T,Green,Beige,None reported,Yes,11999
1362,1362,Ford,Mustang EcoBoost Premium,2016,43000,–,–,A/T,Blue,Black,None reported,Yes,15500
1741,1741,Chevrolet,Protege DX,1993,94200,–,–,A/T,Red,Gray,None reported,Yes,7599
...,...,...,...,...,...,...,...,...,...,...,...,...,...
187399,187399,Mazda,MX-5 Miata Base,1993,90200,–,–,5-Speed M/T,Gray,Black,At least 1 accident or damage reported,Yes,11500
187495,187495,Nissan,Pathfinder SL,2014,87305,–,284.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Brown,Gray,At least 1 accident or damage reported,Yes,10000
187664,187664,Mercedes-Benz,SLS AMG Base,1993,14586,–,–,A/T,Red,Silver,None reported,Yes,65000
187820,187820,Chrysler,Pacifica Touring,2017,57300,–,–,9-Speed A/T,Blue,Black,None reported,Yes,31700
188189,188189,Chrysler,300 Touring,1994,79785,–,–,A/T,Green,Beige,At least 1 accident or damage reported,Yes,9499

In [13]:
df[df['fuel_type'] == 'not supported']

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
4823,4823,Chevrolet,Suburban LT,2011,109646,not supported,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,6-Speed A/T,Black,Beige,None reported,Yes,18998
18000,18000,Porsche,Camaro 2SS,2015,67000,not supported,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,11500
19182,19182,Nissan,Mirai Limited,2000,131000,not supported,182.0HP Electric Motor Hydrogen Fuel,A/T,Silver,Black,None reported,Yes,5000
27199,27199,Subaru,Outback 2.5i Limited,2017,116000,not supported,175.0HP 2.5L 4 Cylinder Engine Gasoline Fuel,CVT Transmission,Gray,Black,At least 1 accident or damage reported,Yes,27499
33030,33030,Nissan,Mirai Limited,2009,137333,not supported,182.0HP Electric Motor Hydrogen Fuel,A/T,White,Gray,At least 1 accident or damage reported,Yes,12999
60717,60717,Chevrolet,Silverado 1500 RST,2020,19200,not supported,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,58000
74096,74096,Toyota,Mirai Limited,2021,79876,not supported,182.0HP Electric Motor Hydrogen Fuel,A/T,Red,Black,None reported,Yes,15000
86897,86897,Lexus,IS 350 F Sport,2022,9500,not supported,311.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes,60000
94425,94425,Porsche,Cayenne Turbo GT,2018,52000,not supported,550.0HP 4.8L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Gray,Gray,At least 1 accident or damage reported,Yes,35000
127066,127066,Toyota,Mirai Limited,2016,58664,not supported,151.0HP Electric Motor Hydrogen Fuel,CVT Transmission,Black,Black,At least 1 accident or damage reported,Yes,22500
128917,128917,Mazda,MX-5 Miata Base,1999,120000,not supported,140.0HP 1.8L 4 Cylinder Engine Gasoline Fuel,5-Speed M/T,Black,Beige,At least 1 accident or damage reported,Yes,4000
135865,135865,Lexus,Mirai Limited,2014,123331,not supported,182.0HP Electric Motor Hydrogen Fuel,A/T,Red,Gray,At least 1 accident or damage reported,Yes,11495
140206,140206,Lexus,RX 330 Base,2006,110000,not supported,230.0HP 3.3L V6 Cylinder Engine Gasoline Fuel,5-Speed A/T,White,Beige,At least 1 accident or damage reported,Yes,9500
171120,171120,Hummer,H2 Base,2013,152068,not supported,316.0HP 6.0L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Black,At least 1 accident or damage reported,Yes,14000
171659,171659,Toyota,Mirai Limited,2021,44000,not supported,182.0HP Electric Motor Hydrogen Fuel,A/T,Gray,Black,None reported,Yes,4900

In [18]:
df_test = func.cleaning_null(df_test)

/home/tiago/Documents/GitHub/Projects/used_car_prices/notebooks/functions.py:51: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.clean_title.fillna('None reported', inplace = True)
/home/tiago/Documents/GitHub/Projects/used_car_prices/notebooks/functions.py:54: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.accident.fillna('No', inplace = True)